// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNzc2CLspvzUGwOQqqci9NKdUkxxZErHs',
    appId: '1:151114193930:web:3cebed891fbe7407ef53f3',
    messagingSenderId: '151114193930',
    projectId: 'chat-material3-ab3c8',
    authDomain: 'chat-material3-ab3c8.firebaseapp.com',
    storageBucket: 'chat-material3-ab3c8.appspot.com',
    measurementId: 'G-7N543TJN3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4C6pB0iG3IUvlt6y37frfl7jLWWR0wE',
    appId: '1:151114193930:android:99b7432eb086b406ef53f3',
    messagingSenderId: '151114193930',
    projectId: 'chat-material3-ab3c8',
    storageBucket: 'chat-material3-ab3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIZ6JvpgQReg52vulDShOxjoGusyWWs4',
    appId: '1:151114193930:ios:c29c66bd6d2b9d68ef53f3',
    messagingSenderId: '151114193930',
    projectId: 'chat-material3-ab3c8',
    storageBucket: 'chat-material3-ab3c8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIZ6JvpgQReg52vulDShOxjoGusyWWs4',
    appId: '1:151114193930:ios:c29c66bd6d2b9d68ef53f3',
    messagingSenderId: '151114193930',
    projectId: 'chat-material3-ab3c8',
    storageBucket: 'chat-material3-ab3c8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNzc2CLspvzUGwOQqqci9NKdUkxxZErHs',
    appId: '1:151114193930:web:4e7383dc36581351ef53f3',
    messagingSenderId: '151114193930',
    projectId: 'chat-material3-ab3c8',
    authDomain: 'chat-material3-ab3c8.firebaseapp.com',
    storageBucket: 'chat-material3-ab3c8.appspot.com',
    measurementId: 'G-K3LKK8D6WN',
  );
}
